import * as mongoose from 'mongoose';
var Schema = mongoose.Schema;

const productSchema = new Schema({
    name:{
        type:String,
        required:true,
        unique:true
    },
    slug:{
        type:String,
        unique:true
    },
    desciption:{
        type:String
    },
    meta_title:{
        type:String
    },
    meta_description:{
        type:String
    },
    meta_keywords:{
        type:String
    },
    tags:{
        type:String
    },
    image:{
        type:String
    },
    model:{
        type:String
    },
    sku:{
        type:String
    },
    upc:{
        type:String
    },
    ean:{
        type:String
    },
    jan:{
        type:String
    },
    isbn:{
        type:String
    },
    mpn:{
        type:String
    },
    location:{
        type:String
    },
    quantity:{
        type:String
    },
    stock_status:{
        type:Schema.ObjectId,
        ref:'Stock'
    },
    manufacturer:{
        type:Schema.ObjectId,
        ref:'Manufacturer'
    },
    shipping:{
        type:Boolean
    },
    price:{
        type:Number,
        required:true
    },
    weight:{
        type:String
    },
    length:{
        type:String
    },
    width:{
        type:String
    },
    height:{
        type:String
    },
    minimum_order_unit:{
        type:Number
    },
    maximum_order_unit:{
        type:Number
    },
    sort_order:{
        type:Number
    },
    status:{
        type:Boolean
    },
    viewed:{
        type:Number
    },
    createdAt:{
        type:Date
    },
    updatedAt:{
        type:Date
    }
});

const Product = mongoose.model('Product', productSchema);
export default Product;